import numpy as np


class Doublet:
    """
    Contains information related to a doublet.
    """

    def __init__(self, strength: float, x: float, y: float):
        """
        Sets the location and strength of the doublet.

        Parameters
        ----------
        strength: float
            Strength of the doublet.
        x: float
            x-coordinate of the doublet.
        y: float
            y-coordinate of the doublet.
        """
        self.strength = strength
        self.x, self.y = x, y

    def velocity(self, x: np.ndarray, y: np.ndarray):
        """
        Computes the velocity field generated by a doublet.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the doublet.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the doublet.
        """
        u = (
            -self.strength
            / (2 * np.pi)
            * ((x - self.x) ** 2 - (y - self.y) ** 2)
            / ((x - self.x) ** 2 + (y - self.y) ** 2) ** 2
        )
        v = (
            -self.strength
            / (2 * np.pi)
            * 2
            * (x - self.x)
            * (y - self.y)
            / ((x - self.x) ** 2 + (y - self.y) ** 2) ** 2
        )
        return u, v

    def stream_function(self, x: np.ndarray, y: np.ndarray):
        """
        Computes the stream-function generated by a doublet.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            stream function generated by the doublet.
        """
        psi = (
            -self.strength
            / (2 * np.pi)
            * (y - self.y)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        return psi
