import numpy as np


class Source:
    """
    Contains information related to a source (or sink).
    """

    def __init__(self, strength: float, x: float, y: float):
        """
        Sets the location and strength of the singularity.

        Parameters
        ----------
        strength: float
            Strength of the singularity.
        x: float
            x-coordinate of the singularity.
        y: float
            y-coordinate of the singularity.
        """
        self.strength = strength
        self.x, self.y = x, y

    def velocity(self, x: np.ndarray, y: np.ndarray):
        """
        Computes the velocity field generated by the singularity.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the source.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the source.
        """
        u = (
            self.strength
            / (2 * np.pi)
            * (x - self.x)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        v = (
            self.strength
            / (2 * np.pi)
            * (y - self.y)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        return u, v

    def stream_function(self, x: np.ndarray, y: np.ndarray):
        """
        Computes the stream-function generated by the singularity.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            stream function generated by the source.
        """
        psi = self.strength / (2 * np.pi) * np.arctan2((y - self.y), (x - self.x))
        return psi
