import numpy as np


class UniformFlow:
    """
    Contains information related to a uniform flow.
    """

    def __init__(self, u_inf: float, alpha: float):
        """
        Sets velocity and angle of attack of the uniform flow.

        Parameters
        ----------
        u_inf: float
            Velocity of the uniform flow.
        alpha: float
            Angle of attack of the uniform flow in degrees.
        """
        self.u_inf = u_inf
        self.alpha = alpha

    def velocity(self, x: np.ndarray, y: np.ndarray):
        """
        Returns the uniform velocity field.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the source.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the source.
        """
        u = self.u_inf * np.cos(np.radians(self.alpha)) * np.full_like(x, 1)
        v = self.u_inf * np.sin(np.radians(self.alpha)) * np.full_like(y, 1)
        return u, v

    def stream_function(self, x: np.ndarray, y: np.ndarray):
        """
        Computes the stream-function uniform flow.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            stream function generated by the source.
        """
        psi = self.u_inf * y * np.cos(np.radians(self.alpha)) - self.u_inf * x * np.sin(
            np.radians(self.alpha)
        )
        return psi
