import numpy as np


class Vortex:
    """
    Contains information related to a vortex.
    """

    def __init__(self, strength: float, x: float, y: float):
        """
        Sets the location and strength of the vortex.

        Parameters
        ----------
        strength: float
            Strength of the vortex.
        x: float
            x-coordinate of the vortex.
        y: float
            y-coordinate of the vortex.
        """
        self.strength = strength
        self.x, self.y = x, y

    def velocity(self, x: np.ndarray, y: np.ndarray):
        """
        Computes the velocity field generated by a vortex.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        u: 2D Numpy array of floats
            x-component of the velocity field generated by the vortex.
        v: 2D Numpy array of floats
            y-component of the velocity field generated by the vortex.
        """
        u = (
            +self.strength
            / (2 * np.pi)
            * (y - self.y)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        v = (
            -self.strength
            / (2 * np.pi)
            * (x - self.x)
            / ((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        return u, v

    def stream_function(self, x: np.ndarray, y: np.ndarray):
        """
        Computes the stream-function generated by a vortex.

        Parameters
        ----------
        x: 2D Numpy array of floats
            x-coordinate of the mesh points.
        y: 2D Numpy array of floats
            y-coordinate of the mesh points.

        Returns
        -------
        psi: 2D Numpy array of floats
            stream function generated by the vortex.
        """
        psi = (
            -self.strength / (4 * np.pi) * np.log((x - self.x) ** 2 + (y - self.y) ** 2)
        )
        return psi
